config/routes.rb
Todo::Application.routes.draw do
  resources :items do
    get :done, :on => :member
  end

  root :to => "items#index"
  
  resource :user_session
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout

end

app/models/item.rb
class Item < ActiveRecord::Base
  
  scope :default_order, order("updated_at DESC")
  scope :todo, default_order.where(:done => false)
  scope :done, default_order.where(:done => true)

  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user_session, :current_user

  protect_from_forgery

  protected

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end

    def require_admin
      if require_user
        unless current_user.role == "admin"
          flash[:notice] = "You must be administrator to access this page"
          redirect_to root_url
          return false
        end
      end
    end

    def require_editor
      if require_user
        unless current_user.role == "editor" or current_user.role == "admin"
          flash[:notice] = "You must be editor to access this page"
          redirect_to root_url
          return false
        end
      end
    end

    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to root_url
        return false
      end
    end

    def store_location
      session[:return_to] = request.fullpath
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :require_user
  
  def index
    @todo = Item.todo
    @done = Item.done
  end
  
  def done
    @item = Item.find(params[:id])
	if @item.done == true
		@item.update_attribute(:done, false)
	else 
		@item.update_attribute(:done, true)
	end

    redirect_to items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item])

    if @item.save
      redirect_to(items_path, :notice => 'Item was successfully created.')
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    
    if @item.update_attributes(params[:item])
      redirect_to(items_path, :notice => 'Item was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    
    redirect_to root_path()
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = I18n.t("user_sessions.notice.logout")
    redirect_back_or_default new_user_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	
	def date_status(item)
		if (Time.now.in_time_zone - item.updated_at.to_datetime)  <= 24.hours 
			time_ago_in_words(item.updated_at)
		elsif(Time.now.in_time_zone - item.updated_at.to_datetime) <= 1.year
			item.updated_at.strftime("%d %b")
		else
			item.update_at.strftime("%d %b %Y")
		end
	end
    
	def button_name(item)
		if item.done?
			button = "Undo"
		else
			button = "Done"
		end
	
	end
end

app/views/items/_form.html.haml
= form_for(@item) do |f|
  

  %h2= @title unless @title == ""
  
  %p.required
    = f.text_field :title, :size => nil, :id => "title", :class => "text title"

  %p.submit
    = f.submit t('action.save'), :class=> 'button'
    %span
      = t('action.or')
      = link_to_function t('action.cancel'), "hideEditor()"

app/views/items/_item.html.haml
%li
  .line-content
    - if !item.done?
      .date
        %span{:class => "date"}= date_status(item) 
      = link_to "#{t('items.show.remember_to')}: #{item.title}", edit_item_path(item), :class => "item", :remote => true
    - else
      .date
        %span{:class => "date"}= date_status(item)
      = link_to "#{t('items.show.done')}: #{item.title}", edit_item_path(item), :class => "item", :remote => true    
    %span= link_to button_name(item), done_item_path(item), :class => "button"
    %span= link_to "Delete", item_path(item), :method => :delete, :confirm => "Are you sure", :class => "button delete"

app/views/items/edit.html.haml
%h1 Editing item
= render 'form'
= link_to 'Show', @item
|
\#{link_to 'Back', items_path}

app/views/items/edit.js.haml
$("#editor").html("#{escape_javascript(render 'form', :title => t('.header'))}");
showEditor();

app/views/items/index.html.haml
#new= link_to t('items.actions.new'), new_item_path, :remote => true

- if @todo.blank?
  %h3= t('items.show.no_open_tasks')
- else
  %ul#projects.todo
    = render :partial => 'item', :collection => @todo

%ul#projects.done
  - unless @done.blank?
    = render :partial => 'item', :collection => @done

app/views/items/new.html.haml
%h1 New item
= render 'form'
= link_to 'Back', items_path

app/views/items/new.js.haml
$("#editor").html("#{escape_javascript(render 'form', :title => t('.header'))}");
showEditor();

app/views/items/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @item.title
%p
  %b Body:
  = @item.body
%p
  %b Done:
  = @item.done
= link_to 'Edit', edit_item_path(@item)
|
\#{link_to 'Back', items_path}

app/views/layouts/application.html.haml
!!!
%html{:lang => "en", "xml:lang" => "en", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}
    %meta{ :content => "en", :"http-equiv" => "Content-Language" }
    %title Todo Application
    
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = stylesheet_link_tag 'reset', 'screen'
    
  %body

    #header
      %div.transparent
        %div.logo
      %h1
        - if current_user
          = "#{current_user.login}#{t('application.add_name_to_username')}"
        - else
          = t('application.title')
      %address.watermark
        = link_to t('action.logout'), user_session_path, :method => :delete if current_user

    #wrapper
      #editor{:style => "display:none;"}

      #content= yield

app/views/user_sessions/new.html.haml
= form_for @user_session, :url => user_session_path, :html => {:class => 'login'} do |f|
  %p.title= t '.login'
  %p.required
    = f.text_field 'login', :size => nil, :id => 'user_login', :class => "text", :placeholder => "User Name"
  %p.required
    = f.password_field 'password', :size => nil, :id => 'user_pass', :class => "text", :placeholder => "Password"
  
  %p.submit
    = f.submit t('action.login'), :class=> 'button'
  %div{:style => "clear:both"}